#alias e 'code'
#alias exip 'curl -s https://ipecho.net/plain'
#alias g 'git'
#alias iaupload 'ia upload --checksum --verify --retries 10 --no-backup'
#alias vts 'echo vitetris --connect (exip):27015 && vitetris -listen 27015'
