players:
  mpv:
    ipc_path: \\.\pipe\mpvsocket
  syncplay@mpv:
    ipc_path: \\.\pipe\\\.\pipe\mpvsocket
  monitored: [mpv, syncplay@mpv]

fileinfo:
  whitelist:
    [
      'E:\non-anime',
      "E:/shared-unruhe\\anime",
      "E:/shared-unruhe\\non-anime",
      "E:/shared-unruhe/non-anime",
      "E:/shared-unruhe/anime",
      'E:\shared-tablet',
      "E:/gccx",
      "E:\\gccx",
    ]
version: "1.0"
