fileinfo:
  whitelist:
    - C:\Users\user\shared-unruhe\non-anime
    - C:/Users/user/shared-unruhe\non-anime
    - C:\Users\user\shared-unruhe-oracle
    - C:/Users/user/shared-unruhe-oracle
    - C:\Users\user\shared-tablet
    - C:\Users\user\torrents\tv
    - C:\Users\user\torrents\movies

players:
  syncplay@mpv:
    ipc_path: \\.\pipe\mpvSyncplaySocket
  monitored: [syncplay@mpv, plex]
version: "1.0"
