players:
  mpv:
    ipc_path: \\.\pipe\mpvsocket
  syncplay@mpv:
    ipc_path: \\.\pipe\\\.\pipe\mpvsocket
  monitored: [mpv, syncplay@mpv]

fileinfo:
  whitelist: ['E:\non-anime', "E:/shared-unruhe", 'E:\shared-tablet', "E:/gccx"]
version: "1.0"
