fileinfo:
  whitelist:
    - C:\Users\ruruo\shared-unruhe\non-anime
    - C:/Users/ruruo/shared-unruhe\non-anime
    - C:\Users\ruruo\shared-unruhe-oracle
    - C:/Users/ruruo/shared-unruhe-oracle
    - C:\Users\ruruo\Downloads\tv
    - C:\Users\ruruo\Downloads\movies

players:
  syncplay@mpv:
    ipc_path: \\.\pipe\mpvSyncplaySocket
  monitored: [syncplay@mpv, plex]
version: "1.0"
